repos:
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.2.2
    hooks:
      - id: gdformat
        name: gdformat (GDScript formatter)
        entry: gdformat
        language: python
        language_version: python3
        require_serial: true
        files: "\\.gd$"
